carbohydrates:
  name: carbohydrates
  emoticon: ğŸ
total_fat:
  name: fats
  emoticon: ğŸ§
protein:
  name: protein
  emoticon: ğŸ—
fiber:
  name: fibre
  emoticon: ğŸ¥¦
sleep_analysis_asleep:
  name: asleep
  emoticon: ğŸŒ’
sleep_analysis_inBed:
  name: in bed
  emoticon: ğŸ›ï¸
sleep_analysis_sleepStart:
  name: bedtime
  emoticon: ğŸ’¤
step_count:
  name: steps
  emoticon: ğŸ‘£
mindful_minutes:
  name: meditation
  emoticon: ğŸ§˜â€â™‚ï¸
apple_exercise_time:
  name: exercise
  emoticon: ğŸš²
weight_body_mass:
  name: weight
  emoticon: ğŸ»
