carbohydrates:
  name: carbohydrates
  units: g
  emoticon: ğŸ
  group: macros
total_fat:
  name: fats
  units: g
  emoticon: ğŸ§
  group: macros
protein:
  name: protein
  units: g
  emoticon: ğŸ—
  group: macros
fiber:
  name: fibre
  units: g
  emoticon: ğŸ¥¦
  group: macros
sleep_analysis_asleep:
  name: asleep
  emoticon: ğŸŒ’
  group: sleep
sleep_analysis_inBed:
  name: in bed
  emoticon: ğŸ›ï¸
  group: sleep
sleep_analysis_sleepStart:
  name: bedtime
  emoticon: ğŸ’¤
  group: sleep_times
step_count:
  name: steps
  emoticon: ğŸ‘£
  units: steps
  group: dailys
mindful_minutes:
  name: meditation
  units: mins
  emoticon: ğŸ§˜â€â™‚ï¸
  group: dailys
apple_exercise_time:
  name: exercise
  units: mins
  emoticon: ğŸš²
  group: dailys
weight_body_mass:
  name: weight
  units: kg
  emoticon: ğŸ»
  group: dailys
